[2025-02-17T06:29:13.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-17T06:29:13.697+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_trino_dag.task_3 manual__2025-02-17T06:29:09.677687+00:00 [queued]>
[2025-02-17T06:29:13.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_trino_dag.task_3 manual__2025-02-17T06:29:09.677687+00:00 [queued]>
[2025-02-17T06:29:13.708+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-17T06:29:13.723+0000] {taskinstance.py:2330} INFO - Executing <Task(TrinoOperator): task_3> on 2025-02-17 06:29:09.677687+00:00
[2025-02-17T06:29:13.730+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-17T06:29:13.732+0000] {standard_task_runner.py:63} INFO - Started process 322 to run task
[2025-02-17T06:29:13.732+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_first_trino_dag', 'task_3', 'manual__2025-02-17T06:29:09.677687+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/my_first_trino_dag.py', '--cfg-path', '/tmp/tmp_dwz_r7x']
[2025-02-17T06:29:13.733+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask task_3
[2025-02-17T06:29:13.782+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_trino_dag.task_3 manual__2025-02-17T06:29:09.677687+00:00 [running]> on host 800d9ac51cc2
[2025-02-17T06:29:13.868+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_trino_dag' AIRFLOW_CTX_TASK_ID='task_3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T06:29:09.677687+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T06:29:09.677687+00:00'
[2025-02-17T06:29:13.869+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-17T06:29:13.882+0000] {trino_operator.py:39} INFO - Creating Trino connection
[2025-02-17T06:29:13.883+0000] {trino_operator.py:48} INFO - Executing single sql statement
[2025-02-17T06:29:13.891+0000] {base.py:84} INFO - Using connection ID 'trino_connection' for task execution.
[2025-02-17T06:29:13.898+0000] {base.py:84} INFO - Using connection ID 'trino_connection' for task execution.
[2025-02-17T06:29:13.901+0000] {unix.py:142} WARNING - /etc/timezone is deprecated on Debian, and no longer reliable. Ignoring.
[2025-02-17T06:29:13.902+0000] {sql.py:511} INFO - Running statement: select { { task_instance.xcom_pull(task_ids='task_1',key='return_value')[0] } }, parameters: None
[2025-02-17T06:29:13.939+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-17T06:29:13.939+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/trino/hooks/trino.py", line 195, in get_first
    return super().get_first(self.strip_sql_string(sql), parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 336, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/trino_operator.py", line 21, in run
    return super(TrinoHook, self).run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/dbapi.py", line 614, in execute
    self._iterator = iter(self._query.execute())
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 900, in execute
    self._result.rows += self.fetch()
                         ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 920, in fetch
    status = self._request.process(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/trino/client.py", line 689, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:8: mismatched input '{'. Expecting: '*', 'ALL', 'DISTINCT', <expression>", query_id=20250217_062915_00022_ct8h8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/trino_operator.py", line 50, in execute
    return hook.get_first(sql, parameters=self.parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/trino/hooks/trino.py", line 197, in get_first
    raise TrinoException(e)
airflow.providers.trino.hooks.trino.TrinoException: TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:8: mismatched input '{'. Expecting: '*', 'ALL', 'DISTINCT', <expression>", query_id=20250217_062915_00022_ct8h8)
[2025-02-17T06:29:13.949+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=my_first_trino_dag, task_id=task_3, run_id=manual__2025-02-17T06:29:09.677687+00:00, execution_date=20250217T062909, start_date=20250217T062913, end_date=20250217T062913
[2025-02-17T06:29:13.959+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task task_3 (TrinoUserError(type=USER_ERROR, name=SYNTAX_ERROR, message="line 1:8: mismatched input '{'. Expecting: '*', 'ALL', 'DISTINCT', <expression>", query_id=20250217_062915_00022_ct8h8); 322)
[2025-02-17T06:29:13.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-17T06:29:14.000+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T06:29:14.002+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
